version: '3'
services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
  appf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'Backend_fastapi'
    volumes:
      - './:/app'
    ports:
      - "8765:8765"
    command:
      - python main.py
    networks:
      - sail
    depends_on:
      - mysql
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local